### ISSUE TITLE
network monitor outputs errors when run naively

### ISSUE THREAD

**Issue by sim590** [savoirfairelinux/opendht#157]
I did try to use the new `network_monitor.py` tool in `python/tools/`, but I keep getting this error:

```
$ python3 ./python/tools/network_monitor.py
Exception in callback listen_cb(<InfoHash '56...936377285695'>, <opendht.Valu...x7f557df4dd90>) at ./network_monitor.py:46
handle: <Handle listen_cb(<InfoHash '56...936377285695'>, <opendht.Valu...x7f557df4dd90>) at ./network_monitor.py:46>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "./network_monitor.py", line 50, in listen_cb
    if pending_tests[kstr].id == val.id:
AttributeError: 'dict' object has no attribute 'id'
Exception in callback listen_cb(<InfoHash 'd6...fd859a3e6ec5'>, <opendht.Valu...x7f557df4ddb0>) at ./network_monitor.py:46
handle: <Handle listen_cb(<InfoHash 'd6...fd859a3e6ec5'>, <opendht.Valu...x7f557df4ddb0>) at ./network_monitor.py:46>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "./network_monitor.py", line 50, in listen_cb
    if pending_tests[kstr].id == val.id:
AttributeError: 'dict' object has no attribute 'id'
Exception in callback listen_cb(<InfoHash '51...a60b956ad11f'>, <opendht.Valu...x7f557df4df90>) at ./network_monitor.py:46
handle: <Handle listen_cb(<InfoHash '51...a60b956ad11f'>, <opendht.Valu...x7f557df4df90>) at ./network_monitor.py:46>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "./network_monitor.py", line 50, in listen_cb
    if pending_tests[kstr].id == val.id:
AttributeError: 'dict' object has no attribute 'id'
Exception in callback listen_cb(<InfoHash '70...bfd2910a8281'>, <opendht.Valu...x7f557df4de90>) at ./network_monitor.py:46
handle: <Handle listen_cb(<InfoHash '70...bfd2910a8281'>, <opendht.Valu...x7f557df4de90>) at ./network_monitor.py:46>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "./network_monitor.py", line 50, in listen_cb
    if pending_tests[kstr].id == val.id:
AttributeError: 'dict' object has no attribute 'id'
Exception in callback listen_cb(<InfoHash '58...dfb1d4859eee'>, <opendht.Valu...x7f557df4df30>) at ./network_monitor.py:46
handle: <Handle listen_cb(<InfoHash '58...dfb1d4859eee'>, <opendht.Valu...x7f557df4df30>) at ./network_monitor.py:46>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "./network_monitor.py", line 50, in listen_cb
    if pending_tests[kstr].id == val.id:
AttributeError: 'dict' object has no attribute 'id'
Exception in callback listen_cb(<InfoHash '12...cb6ce86be4ed'>, <opendht.Valu...x7f557df4dbd0>) at ./network_monitor.py:46
handle: <Handle listen_cb(<InfoHash '12...cb6ce86be4ed'>, <opendht.Valu...x7f557df4dbd0>) at ./network_monitor.py:46>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "./network_monitor.py", line 50, in listen_cb
    if pending_tests[kstr].id == val.id:
AttributeError: 'dict' object has no attribute 'id'
Exception in callback listen_cb(<InfoHash 'ca...e64a40ad8f04'>, <opendht.Valu...x7f557df4dbf0>) at ./network_monitor.py:46
handle: <Handle listen_cb(<InfoHash 'ca...e64a40ad8f04'>, <opendht.Valu...x7f557df4dbf0>) at ./network_monitor.py:46>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "./network_monitor.py", line 50, in listen_cb
    if pending_tests[kstr].id == val.id:
AttributeError: 'dict' object has no attribute 'id'
^CTraceback (most recent call last):
  File "./network_monitor.py", line 73, in <module>
    time.sleep(1)
KeyboardInterrupt
```

**Comment by aberaud** [comment]
fixed by 0fd4f73ab1dc503ce53a18db4f7569f4f92f6cf8
