### ISSUE TITLE
[scanner.py] crash float object

### ISSUE THREAD

**Issue by ChristopheMotte** [savoirfairelinux/opendht#173]
Simply running the scanner on mac and on linux.

```
Traceback (most recent call last):
  File "./scanner.py", line 249, in <module>
    update_plot()
  File "./scanner.py", line 230, in update_plot
    offsets = xys, transOffset = ringx.transData))
  File "/usr/local/lib/python3.6/site-packages/matplotlib/collections.py", line 1062, in __init__
    self._paths = [self._path_generator(numsides)]
  File "/usr/local/lib/python3.6/site-packages/matplotlib/path.py", line 666, in unit_regular_polygon
    np.arange(numVertices + 1).reshape((numVertices + 1, 1)))
TypeError: 'float' object cannot be interpreted as an integer
```

**Comment by aberaud** [comment]
fixed in e98f06e84a6c79d50a05845244edc56861efed32
