### ISSUE TITLE
Crash when using ring-daemon

### ISSUE THREAD

**Issue by szotsaki** [savoirfairelinux/opendht#203]
When I start `dring`, opendht crashes right at the start sequence. I don't know if it's a dring issue or an opendht one, but the top of the stack made me post it here first :).

Opendht version: 1.3.4.

```
#0  std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string (this=this@entry=0x7ffff41abe50 <dht::indexation::IndexEntry::TYPE+16>, 
    __str=<error reading variable: Cannot access memory at address 0xffffffffffffffe8>) at /usr/src/debug/gcc-6.2.1-r239768/obj-x86_64-suse-linux/x86_64-suse-linux/libstdc++-v3/include/bits/basic_string.tcc:613
#1  0x00007ffff3f37c52 in dht::ValueType::ValueType(dht::ValueType const&) [clone .lto_priv.770] (this=this@entry=0x7ffff41abe40 <dht::indexation::IndexEntry::TYPE>) at /usr/src/debug/opendht-1.3.4/include/opendht/value.h:74
#2  0x00007ffff3f0253d in __static_initialization_and_destruction_0 (__initialize_p=1, __priority=65535) at /usr/src/debug/opendht-1.3.4/src/indexation/pht.cpp:148
#3  _GLOBAL__sub_I_pht.cpp.lto_priv.550 () at /usr/src/debug/opendht-1.3.4/src/indexation/pht.cpp:538
#4  0x00007ffff3f02aee in _GLOBAL__I_65535_0_utils.cpp.o () from /usr/lib64/libopendht.so.1
#5  0x00007ffff7deacba in call_init (l=<optimized out>, argc=argc@entry=1, argv=argv@entry=0x7fffffffd988, env=env@entry=0x7fffffffd998) at dl-init.c:72
#6  0x00007ffff7deada3 in call_init (env=0x7fffffffd998, argv=0x7fffffffd988, argc=1, l=<optimized out>) at dl-init.c:30
#7  _dl_init (main_map=0x7ffff7ffe148, argc=1, argv=0x7fffffffd988, env=0x7fffffffd998) at dl-init.c:120
#8  0x00007ffff7ddd22a in _dl_start_user () from /lib64/ld-linux-x86-64.so.2
#9  0x0000000000000001 in ?? ()
#10 0x00007fffffffdedf in ?? ()
#11 0x0000000000000000 in ?? ()
```

**Comment by szotsaki** [comment]
This issue is in 1.3.6, too.

**Comment by aberaud** [comment]
Hi,
Do you still have this bug with latest release ?
Will investigate, however as a temporary workaround I suggest to disable LTO.
Thanks

**Comment by szotsaki** [comment]
Yes, I have it with 1.4.1, too. I upgraded the compiler from GCC 5 to GCC 6.2.1 but the issue stayed the same. Current backtrace:

```
#0  0x00007ffff741eb8b in std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::string const&) () from /usr/lib64/libstdc++.so.6 
#1  0x00007ffff3fea472 in dht::ValueType::ValueType(dht::ValueType const&) [clone .lto_priv.775] (this=0x7ffff424db20 <dht::indexation::IndexEntry::TYPE>) at /usr/src/debug/opendht-1.4.1/include/opendht/value.h:75 
#2  0x00007ffff3fa6cad in __static_initialization_and_destruction_0 (__initialize_p=1, __priority=65535) at /usr/src/debug/opendht-1.4.1/src/indexation/pht.cpp:148 
#3  _GLOBAL__sub_I_pht.cpp.lto_priv.552 () at /usr/src/debug/opendht-1.4.1/src/indexation/pht.cpp:538 
#4  0x00007ffff3fa6eae in _GLOBAL__I_65535_0_utils.cpp.o () from /usr/lib64/libopendht.so.1 
#5  0x00007ffff7deacba in call_init (l=<optimized out>, argc=argc@entry=1, argv=argv@entry=0x7fffffffd9d8, env=env@entry=0x7fffffffd9e8) at dl-init.c:72 
#6  0x00007ffff7deada3 in call_init (env=0x7fffffffd9e8, argv=0x7fffffffd9d8, argc=1, l=<optimized out>) at dl-init.c:30 
#7  _dl_init (main_map=0x7ffff7ffe148, argc=1, argv=0x7fffffffd9d8, env=0x7fffffffd9e8) at dl-init.c:120 
#8  0x00007ffff7ddd22a in _dl_start_user () from /lib64/ld-linux-x86-64.so.2 
#9  0x0000000000000001 in ?? () 
#10 0x00007fffffffdf16 in ?? () 
#11 0x0000000000000000 in ?? ()
```

I'll try it without LTO.

**Comment by szotsaki** [comment]
1.5.0 with today's latest ring-daemon works fine with LTO disabled.

**Comment by ghenry** [comment]
Closing. Thanks!
