### ISSUE TITLE
100% and blocks when listening the dht

### ISSUE THREAD

**Issue by AmarOk1412** [savoirfairelinux/opendht#229]
Currently benchmarking a proxy.

On one node, the proxy got 8000 LISTEN on different hashes on the DHT. The other node is litterally spamming these hashes.

After ~15 to 30 minutes, the proxy stop responding on endpoints which retrieves datas from the DHT, and the OpenDHT main thread takes 100% of one core. Can't use this node to put or get datas.

The best backtrace I found so far is:
```
#0  0x00007ffff78f8736 in dht::Dht::Search::currentlySolicitedNodeCount() const ()
   from /root/ansible/src/opendht/build/libopendht.so.1
#1  0x00007ffff78e77b1 in dht::Dht::searchSendGetValues(std::shared_ptr<dht::Dht::Search>, dht::Dht::SearchNode*, bool) () from /root/ansible/src/opendht/build/libopendht.so.1
#2  0x00007ffff78ed49f in dht::Dht::searchStep(std::shared_ptr<dht::Dht::Search>) ()
   from /root/ansible/src/opendht/build/libopendht.so.1
#3  0x00007ffff78fa4ff in std::_Function_handler<void (), std::_Bind<std::_Mem_fn<void (dht::Dht::*)(std::shared_ptr<dht::Dht::Search>)> (dht::Dht*, std::shared_ptr<dht::Dht::Search>)> >::_M_invoke(std::_Any_data const&) () from /root/ansible/src/opendht/build/libopendht.so.1
#4  0x00007ffff78d7f44 in dht::Dht::periodic(unsigned char const*, unsigned long, dht::SockAddr const&) () from /root/ansible/src/opendht/build/libopendht.so.1
#5  0x00007ffff78fa472 in dht::Dht::periodic(unsigned char const*, unsigned long, sockaddr const*, unsigned int) () from /root/ansible/src/opendht/build/libopendht.so.1
```

**Comment by AmarOk1412** [comment]
Ok edit. Nothing to do with spamming the DHT, just listening (without any proxy) :

`(python -c "for i in range(0, 8000): print('l ' + str(i)) " && cat) | ./tools/dhtnode -b bootstrap.ring.cx`

and just wait ~ 15 min, the opendht process will block and then you can do any operations on the DHT.

**Comment by AmarOk1412** [comment]
Can't see this problem on the proxy and this proxy is running since some weeks for now. So I close this.
