### ISSUE TITLE
AddressSanitizer: odr-violation

### ISSUE THREAD

**Issue by vindicatorr** [savoirfairelinux/opendht#550]
I guess I spoke too soon about the success in my gitlab report...
```
$ ./tools/dhtscanner --help
=================================================================
==42014==ERROR: AddressSanitizer: odr-violation (0x5caed5bfbaa0):
  [1] size=16 '__tag' /usr/include/c++/10.2.0/bits/shared_ptr_base.h:513:48
  [2] size=16 '__tag' /usr/include/c++/10.2.0/bits/shared_ptr_base.h:513:48
These globals were registered at these points:
  [1]:
    #0 0x773589fe469a in __asan_register_globals /build/gcc/src/gcc/libsanitizer/asan/asan_globals.cpp:341
    #1 0x5caed5bf855c in __libc_csu_init (/<pathTo>/opendht/build/tools/dhtscanner+0x1c55c)

  [2]:
    #0 0x773589fe469a in __asan_register_globals /build/gcc/src/gcc/libsanitizer/asan/asan_globals.cpp:341
    #1 0x77358a9b6e8d in call_init.part.0 (/lib64/ld-linux-x86-64.so.2+0xfe8d)

==42014==HINT: if you don't care about these errors you may set ASAN_OPTIONS=detect_odr_violation=0
SUMMARY: AddressSanitizer: odr-violation: global '__tag' at /usr/include/c++/10.2.0/bits/shared_ptr_base.h:513:48
==42014==ABORTING
```

I don't remember if I first came across this by trying to run the gnome client or manually running dring, but in the end, I came back to opendht having this issue.
Again, I always try to use the latest you provide: commit f4c6c54a08d9399c6b84bad0ee211ca7436ac180

**Comment by ghenry** [comment]
Still an issue in latest?  

Thanks.
