### ISSUE TITLE
dhtproxy in jami-qt segfaults

### ISSUE THREAD

**Issue by ArchangeGabriel** [savoirfairelinux/opendht#624]
I’m running jami-qt and jami-daemon from latest release, built on Arch against opendht 2.4.7.2. When I enable the DHT proxy, jami-qt segfaults (and then segfaults on start until I manually edit the config file).

Here is a partial backtrace:
```
#0  0x00007fffe691e1f9 in dht::DhtRunner::run(dht::DhtRunner::Config const&, dht::DhtRunner::Context&&) () at /usr/lib/libopendht.so.2
#1  0x00007fffea6f39a3 in jami::JamiAccount::doRegister_() () at /usr/lib/libjami.so.13
#2  0x00007fffea716034 in  () at /usr/lib/libjami.so.13
#3  0x00007fffea860701 in jami::ScheduledExecutor::loop() () at /usr/lib/libjami.so.13
#4  0x00007fffea860809 in  () at /usr/lib/libjami.so.13
#5  0x00007fffea399183 in std::execute_native_thread_routine(void*) (__p=0x555555ec1b50) at /usr/src/debug/gcc/libstdc++-v3/src/c++11/thread.cc:82
#6  0x00007fffea03c54d in  () at /usr/lib/libc.so.6
#7  0x00007fffea0c1874 in clone () at /usr/lib/libc.so.6
```

**Comment by AmarOk1412** [comment]
2.4.9 is fixed (https://github.com/savoirfairelinux/opendht/commit/c6b4e317df280c16a75064f93951d69045220725)
