### ISSUE TITLE
Crash in dht insertNode

### ISSUE THREAD

**Issue by AmarOk1412** [savoirfairelinux/opendht#656]
Don't have a scenario and first time I see this one.

```
Thread 90 "jami" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffe83fff640 (LWP 133260)]
0x00007fffe992732a in dht::Dht::Search::insertNode (this=0x7ffe7ca5d9e0, snode=std::shared_ptr<dht::Node> (use count 16, weak count 1) = {...}, now=..., token=std::vector of length 32, capacity 32 = {...}) at /home/sblin/Projects/jami-project/client-qt/daemon/contrib/native/opendht/src/search.h:862
862	        (*n)->candidate = false;
(gdb) bt
#0  0x00007fffe992732a in dht::Dht::Search::insertNode(std::shared_ptr<dht::Node> const&, std::chrono::time_point<std::chrono::_V2::steady_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >, std::vector<unsigned char, std::allocator<unsigned char> > const&)
    (this=0x7ffe7ca5d9e0, snode=std::shared_ptr<dht::Node> (use count 16, weak count 1) = {...}, now=..., token=std::vector of length 32, capacity 32 = {...})
    at /home/sblin/Projects/jami-project/client-qt/daemon/contrib/native/opendht/src/search.h:862
#1  0x00007fffe9932390 in dht::Dht::searchNodeGetDone(dht::net::Request const&, dht::net::RequestAnswer&&, std::weak_ptr<dht::Dht::Search>, std::shared_ptr<dht::Query>)
    (this=0x7ffec4002320, req=..., answer=..., ws=std::weak_ptr<dht::Dht::Search> (use count 2, weak count 40) = {...}, query=std::shared_ptr<dht::Query> (use count 4997, weak count 0) = {...})
    at dht.cpp:275
#2  0x00007fffe99478f4 in std::__invoke_impl<void, void (dht::Dht::*&)(dht::net::Request const&, dht::net::RequestAnswer&&, std::weak_ptr<dht::Dht::Search>, std::shared_ptr<dht::Query>), dht::Dht*&, dht::net::Request const&, dht::net::RequestAnswer, std::weak_ptr<dht::Dht::Search>&, std::shared_ptr<dht::Query>&>(std::__invoke_memfun_deref, void (dht::Dht::*&)(dht::net::Request const&, dht::net::RequestAnswer&&, std::weak_ptr<dht::Dht::Search>, std::shared_ptr<dht::Query>), dht::Dht*&, dht::net::Request const&, dht::net::RequestAnswer&&, std::weak_ptr<dht::Dht::Search>&, std::shared_ptr<dht::Query>&) (__t=<optimized out>, __f=<optimized out>) at /usr/include/c++/11/bits/invoke.h:74
#3  std::__invoke<void (dht::Dht::*&)(dht::net::Request const&, dht::net::RequestAnswer&&, std::weak_ptr<dht::Dht::Search>, std::shared_ptr<dht::Query>), dht::Dht*&, dht::net::Request const&, dht::net::RequestAnswer, std::weak_ptr<dht::Dht::Search>&, std::shared_ptr<dht::Query>&>(void (dht::Dht::*&)(dht::net::Request const&, dht::net::RequestAnswer&&, std::weak_ptr<dht::Dht::Search>, std::shared_ptr<dht::Query>), dht::Dht*&, dht::net::Request const&, dht::net::RequestAnswer&&, std::weak_ptr<dht::Dht::Search>&, std::shared_ptr<dht::Query>&) (__fn=<optimized out>)
    at /usr/include/c++/11/bits/invoke.h:96
#4  std::_Bind<void (dht::Dht::*(dht::Dht*, std::_Placeholder<1>, std::_Placeholder<2>, std::weak_ptr<dht::Dht::Search>, std::shared_ptr<dht::Query>))(dht::net::Request const&, dht::net::RequestAnswer&&, std::weak_ptr<dht::Dht::Search>, std::shared_ptr<dht::Query>)>::__call<void, dht::net::Request const&, dht::net::RequestAnswer&&, 0ul, 1ul, 2ul, 3ul, 4ul>(std::tuple<dht::net::Request const&, dht::net::RequestAnswer&&>&&, std::_Index_tuple<0ul, 1ul, 2ul, 3ul, 4ul>) (__args=..., this=<optimized out>)
    at /usr/include/c++/11/functional:420
#5  std::_Bind<void (dht::Dht::*(dht::Dht*, std::_Placeholder<1>, std::_Placeholder<2>, std::weak_ptr<dht::Dht::Search>, std::shared_ptr<dht::Query>))(dht::net::Request const&, dht::net::RequestAnswer&&, std::weak_ptr<dht::Dht::Search>, std::shared_ptr<dht::Query>)>::operator()<dht::net::Request const&, dht::net::RequestAnswer, void>(dht::net::Request const&, dht::net::RequestAnswer&&)
    (this=<optimized out>) at /usr/include/c++/11/functional:503
#6  std::__invoke_impl<void, std::_Bind<void (dht::Dht::*(dht::Dht*, std::_Placeholder<1>, std::_Placeholder<2>, std::weak_ptr<dht::Dht::Search>, std::shared_ptr<dht::Query>))(dht::net::Request const&, dht::net::RequestAnswer&&, std::weak_ptr<dht::Dht::Search>, std::shared_ptr<dht::Query>)>&, dht::net::Request const&, dht::net::RequestAnswer>(std::__invoke_other, std::_Bind<void (dht::Dht::*(dht::Dht*, std::_Placeholder<1>, std::_Placeholder<2>, std::weak_ptr<dht::Dht::Search>, std::shared_ptr<dht::Query>))(dht::net::Request const&, dht::net::RequestAnswer&&, std::weak_ptr<dht::Dht::Search>, std::shared_ptr<dht::Query>)>&, dht::net::Request const&, dht::net::RequestAnswer&&) (__f=<optimized out>)
    at /usr/include/c++/11/bits/invoke.h:61
#7  std::__invoke_r<void, std::_Bind<void (dht::Dht::*(dht::Dht*, std::_Placeholder<1>, std::_Placeholder<2>, std::weak_ptr<dht::Dht::Search>, std::shared_ptr<dht::Query>))(dht::net::Request const&, dht::net::RequestAnswer&&, std::weak_ptr<dht::Dht::Search>, std::shared_ptr<dht::Query>)>&, dht::net::Request const&, dht::net::RequestAnswer>(std::_Bind<void (dht::Dht::*(dht::Dht*, std::_Placeholder<1>, std::_Placeholder<2>, std::weak_ptr<dht::Dht::Search>, std::shared_ptr<dht::Query>))(dht::net::Request const&, dht::net::RequestAnswer&&, std::weak_ptr<dht::Dht::Search>, std::shared_ptr<dht::Query>)>&, dht::net::Request const&, dht::net::RequestAnswer&&) (__fn=<optimized out>)
    at /usr/include/c++/11/bits/invoke.h:111
#8  std::_Function_handler<void (dht::net::Request const&, dht::net::RequestAnswer&&), std::_Bind<void (dht::Dht::*(dht::Dht*, std::_Placeholder<1>, std::_Placeholder<2>, std::weak_ptr<dht::Dht::Search>--Type <RET> for more, q to quit, c to continue without paging--
, std::shared_ptr<dht::Query>))(dht::net::Request const&, dht::net::RequestAnswer&&, std::weak_ptr<dht::Dht::Search>, std::shared_ptr<dht::Query>)> >::_M_invoke(std::_Any_data const&, dht::net::Request const&, dht::net::RequestAnswer&&) (__functor=<optimized out>, __args#0=..., __args#1=...)
    at /usr/include/c++/11/bits/std_function.h:290
#9  0x00007fffe9964c3c in std::function<void (dht::net::Request const&, dht::net::RequestAnswer&&)>::operator()(dht::net::Request const&, dht::net::RequestAnswer&&) const
    (__args#1=..., __args#0=..., this=0x7ffe7c2005d0) at /usr/include/c++/11/bits/std_function.h:590
#10 operator() (msg=<optimized out>, req_status=..., __closure=0x7ffe7c2005d0)
    at network_engine.cpp:789
#11 std::__invoke_impl<void, dht::net::NetworkEngine::sendFindNode(dht::Sp<dht::Node>&, const InfoHash&, dht::want_t, dht::net::NetworkEngine::RequestCb&&, dht::net::NetworkEngine::RequestExpiredCb&&)::<lambda(const dht::net::Request&, dht::net::ParsedMessage&&)>&, const dht::net::Request&, dht::net::ParsedMessage> (__f=...) at /usr/include/c++/11/bits/invoke.h:61
#12 std::__invoke_r<void, dht::net::NetworkEngine::sendFindNode(dht::Sp<dht::Node>&, const InfoHash&, dht::want_t, dht::net::NetworkEngine::RequestCb&&, dht::net::NetworkEngine::RequestExpiredCb&&)::<lambda(const dht::net::Request&, dht::net::ParsedMessage&&)>&, const dht::net::Request&, dht::net::ParsedMessage> (__fn=...) at /usr/include/c++/11/bits/invoke.h:111
#13 std::_Function_handler<void(const dht::net::Request&, dht::net::ParsedMessage&&), dht::net::NetworkEngine::sendFindNode(dht::Sp<dht::Node>&, const InfoHash&, dht::want_t, dht::net::NetworkEngine::RequestCb&&, dht::net::NetworkEngine::RequestExpiredCb&&)::<lambda(const dht::net::Request&, dht::net::ParsedMessage&&)> >::_M_invoke(const std::_Any_data &, const dht::net::Request &, dht::net::ParsedMessage &&) (__functor=<optimized out>, __args#0=..., __args#1=<optimized out>)
    at /usr/include/c++/11/bits/std_function.h:290
#14 0x00007fffe9975af4 in std::function<void (dht::net::Request const&, dht::net::ParsedMessage&&)>::operator()(dht::net::Request const&, dht::net::ParsedMessage&&) const
    (__args#1=<optimized out>, __args#0=..., this=0x7ffe7c99e7a0)
    at /usr/include/c++/11/bits/std_function.h:590
#15 dht::net::Request::setDone(dht::net::ParsedMessage&&) (msg=<optimized out>, this=0x7ffe7c99e760)
    at /home/sblin/Projects/jami-project/client-qt/daemon/contrib/native/opendht/src/request.h:99
#16 dht::net::NetworkEngine::process(std::unique_ptr<dht::net::ParsedMessage, std::default_delete<dht::net::ParsedMessage> >&&, dht::SockAddr const&) (this=this@entry=0x7ffec4002fb8, msg=..., from=...)
    at network_engine.cpp:588
#17 0x00007fffe9977b07 in dht::net::NetworkEngine::processMessage(unsigned char const*, unsigned long, dht::SockAddr)
    (this=this@entry=0x7ffec4002fb8, buf=0x555557505460 "\204\241r\204\242id\304\024%s\310.\243\275\222\063T;\002\212\b\314vV\021n\225$\242sa\304\004\320Xn.\242n4\304\320\061\064\271@\220\320 \222\022\322\b\350]{\031J\227뇲3M\311[\020\231\064\207)\177\275u\347\335(\370\257)\035\217\062\315 \b\b%3&(\322\020\225\066ֳ\277\237t\345\247J\367\213\304\364\016H\235\253\314\071n6$\262\024\274\206\070h\274WuW\020\352\033\261N\223\001\256MG\f\\\234\374\063[K\230\355\316\071\361\274\231L|\203/\324\370\322\350ێ\216\332\062\036\211\313\063[K\230\224\325<\341\205m&g\354G\350O\213\"\234\213\256\372\236nC(6$\262\024\020\232<"..., buflen=<optimized out>, f=...) at network_engine.cpp:489
#18 0x00007fffe991d877 in dht::Dht::periodic(unsigned char const*, unsigned long, dht::SockAddr, std::chrono::time_point<std::chrono::_V2::steady_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > > const&)
    (this=0x7ffec4002320, buf=<optimized out>, buflen=<optimized out>, from=..., now=<optimized out>) at dht.cpp:2005
#19 0x00007fffe9897639 in dht::SecureDht::periodic(unsigned char const*, unsigned long, dht::SockAddr, std::chrono::time_point<std::chrono::_V2::steady_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > > const&)
    (now=..., sa=..., buflen=<optimized out>, buf=<optimized out>, this=<optimized out>)
    at ../include/opendht/securedht.h:208
#20 dht::DhtRunner::loop_() (this=0x7ffee0002820) at dhtrunner.cpp:673
#21 0x00007fffe9897afd in operator()() const (__closure=0x7ffefc4363b8) at dhtrunner.cpp:195
#22 0x00007fffe9897cff in std::__invoke_impl<void, dht::DhtRunner::run(const dht::DhtRunner::Config&,--Type <RET> for more, q to quit, c to continue without paging--
 dht::DhtRunner::Context&&)::<lambda()> > (__f=<optimized out>)
    at /usr/include/c++/11/bits/invoke.h:60
#23 std::__invoke<dht::DhtRunner::run(const dht::DhtRunner::Config&, dht::DhtRunner::Context&&)::<lambda()> > (__fn=<optimized out>) at /usr/include/c++/11/bits/invoke.h:96
#24 std::thread::_Invoker<std::tuple<dht::DhtRunner::run(const dht::DhtRunner::Config&, dht::DhtRunner::Context&&)::<lambda()> > >::_M_invoke<0> (this=<optimized out>)
    at /usr/include/c++/11/bits/std_thread.h:253
#25 std::thread::_Invoker<std::tuple<dht::DhtRunner::run(const dht::DhtRunner::Config&, dht::DhtRunner::Context&&)::<lambda()> > >::operator() (this=<optimized out>)
    at /usr/include/c++/11/bits/std_thread.h:260
#26 std::thread::_State_impl<std::thread::_Invoker<std::tuple<dht::DhtRunner::run(const dht::DhtRunner::Config&, dht::DhtRunner::Context&&)::<lambda()> > > >::_M_run(void) (this=<optimized out>)
    at /usr/include/c++/11/bits/std_thread.h:211
#27 0x00007fffe8b522b3 in  () at /lib/x86_64-linux-gnu/libstdc++.so.6
#28 0x00007fffe87dbb43 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#29 0x00007fffe886da00 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
(gdb) 

```

(n = 0x0)

**Comment by aberaud** [comment]
fixed
